config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'games#index'
  resources :games do
    member do
      get :guess_place
      get :vote_for_spy
    end
  end
  resources :players, only: %i[create destroy] do
    collection do
      get :get_ready
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user, foreign_key: :create_user_id
  has_many :players, dependent: :delete_all
  has_and_belongs_to_many :places, dependent: :delete_all
  belongs_to :current_place, class_name: 'Place', foreign_key: :current_place_id, optional: true

  validates :title, :password, :create_user_id, presence: true
  after_update_commit do |game|
    # broadcast_update_to :game_show, target: game, locals: { game: self, user: User.current, player: User.current.players.find_by(game_id: self.id) }
    # game.players.each do |player|
    #   broadcast_update_to game, target: "game_id_#{game.id}-player_id#{player.id}", locals: { game: self, user: User.current, player: User.current.players.find_by(game_id: self.id) }
    #   # game.broadcast_action(:update, locals: { user: player.user, player: player })
    # end
  end
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :game_id, :user_id, presence: true

  def full_name
    user.email
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @player = current_user.players.find_by(game_id: @game.id)

    redirect_to games_path unless @game.create_user_id == current_user.id || @player
  end

  def new
    @game = Game.new
  end

  def create
    Game.create(game_params.merge(create_user_id: current_user.id))

    redirect_to games_path
  end

  def update
    game = Game.find(params[:id])
    game.update(game_params)
    # player = game.players.find_by(user_id: current_user.id)

    game.players.each do |player|
      Turbo::StreamsChannel.broadcast_action_to(
        "game_id_#{game.id}-player_id#{player.id}", # na jaki kanal ma isc odpowiedz app/views/games/show.html.erb:1
        action: :update, # co sie ma stac, czy frame ma byc zupdatdowany, czy ma byc usuniety... https://github.com/hotwired/turbo-rails/blob/main/app/models/concerns/turbo/broadcastable.rb
        target: game, # tutaj okreslamy jaki frame ma zostac zupdatowany app/views/games/_game.erb:1
        partial: 'games/game', # jaki partial ma byc wyrederowany
        locals: { game: game, user: player.user, player: player } # jakie paramsy maja trafic do partiala
      )
    end

    redirect_to game
  end

  def edit
    @game = Game.find(params[:id])
  end

  def destroy
    Game.find(params[:id]).destroy

    redirect_to games_path, status: :see_other
  end

  def guess_place
    @game = Game.find(params[:id])
    @player = Player.find_by(user_id: current_user.id, game_id: @game.id)
    if params[:place_id].to_i == @game.current_place.id
      @player.update(score: @player.score + 3)
    else
      @game.players.where.not(id: @player.id).each { |player| player.update(score: player.score + 1) }
    end
    ResetRound.call(@game)

    redirect_to game_path(@game.id)
  end

  def vote_for_spy
    @game = Game.find(params[:id])
    @player = Player.find(params[:spy_id])
    if @player.is_spy?
      @game.players.where.not(id: @player.id).each { |player| player.update(score: player.score + 2) }
    else
      @player.update(score: @player.score + 3)
    end
    ResetRound.call(@game)

    redirect_to game_path(@game.id)
  end

  private

  def game_params
    params.require(:game).permit(:title, :password)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  def create
    Player.create(
      game_id: params[:game_id],
      user_id: current_user.id
    )

    redirect_to game_path(params[:game_id])
  end

  def destroy
    Player.find_by(user_id: current_user.id, game_id: params[:game_id]).destroy

    redirect_to games_path, status: :see_other
  end

  def get_ready
    Player.find_by(user_id: current_user.id, game_id: params[:game_id]).update(is_ready: true)
    game = Game.find(params[:game_id])

    ResetRound.call(game) if game.players.all?(&:is_ready?)

    redirect_to game_path(params[:game_id])
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_)
    games_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/games/_buttons.erb
<%= turbo_frame_tag 'game-buttons' do %>
  <% if player&.is_ready? %>
    <div class="w-auto p-4 bg-gradient-to-tr from-zinc-400 to-zinc-350 py-2 rounded-md text-lg tracking-wide">
      Start
    </div>
  <% else %>
    <%= link_to 'Start', get_ready_players_path(game_id: game.id), class: 'w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide' %>
  <% end %>
<% end %>

app/views/games/_form.html.erb
<%= form_with model: game do |f| %>
  <div class="bg-white px-10 py-8 rounded-xl w-screen shadow-md max-w-sm">
    <div class="space-y-4">
      <h1 class="text-center text-2xl font-semibold text-gray-600"><%= header %></h1>
      <div>
        <label for="email" class="block mb-1 text-gray-600 font-semibold">Name</label>
        <%= f.text_field :title, class: "bg-indigo-50 px-4 py-2 outline-none rounded-md w-full" %>
      </div>
      <div>
        <label for="email" class="block mb-1 text-gray-600 font-semibold">Password</label>
        <%= f.text_field :password, class: "bg-indigo-50 px-4 py-2 outline-none rounded-md w-full" %>
      </div>
    </div>
    <%= f.submit 'Save', class: "mt-4 w-full bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide" %>
  </div>
<% end %>

app/views/games/_game.erb
<%= turbo_frame_tag game, class: "flex flex-col h-full" do %>
  <div class="p-4 mh-4">
    <div class="text-center text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">
      <%= game.title %>
    </div>
    <div class="flex w-full space-x-4 items-stretch place-content-between">
      <%if game.create_user_id == user&.id %>
        <%= link_to 'Edit', edit_game_path(game), class: 'w-auto p-4 bg-gradient-to-tr from-amber-600 to-amber-300 text-indigo-100 py-2 rounded-md text-lg tracking-wide' %>
      <% end %>
      <% if player&.is_ready? %>
        <div class="w-auto p-4 bg-gradient-to-tr from-zinc-400 to-zinc-350 py-2 rounded-md text-lg tracking-wide">
          Start
        </div>
      <% else %>
        <%= link_to 'Start', get_ready_players_path(game_id: game.id), class: 'w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide' %>
      <% end %>
      <%= link_to 'Leave', player_path(player), class: 'w-auto p-4 bg-gradient-to-tr from-red-600 to-red-300 text-indigo-100 py-2 rounded-md text-lg tracking-wide', data: { turbo_method: :delete } %>
    </div>
  </div>
  <div class="grid grid-cols-2 gap-4 h-3/6">
    <div class="flex flex-col overflow-y-auto">
      <% if game.is_started? %>
        <div class="flex flex-col">
          <% if player&.is_spy? %>
            <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
              <header class="px-5 py-4 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800 text-center">
                  <span>
                    You are SPY
                  </span>
                </h2>
              </header>
            </div>
            <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
              <header class="px-5 py-4 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800 text-center">
                  <span>
                    Guess place
                  </span>
                </h2>
              </header>
            </div>
            <% Place.all.each do |place| %>
              <%= link_to "#{place.name}", guess_place_game_path(id: game.id, place_id: place.id), class: 'text-center w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide mb-1' %>
            <% end %>
          <% else %>
            <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
              <header class="px-5 py-4 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800 text-center">
                  <span>
                    You are in/on:
                  </span>
                  <span class="w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide mb-1">
                    <%= game.current_place.name %>
                  </span>
                </h2>
              </header>
            </div>
            <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
              <header class="px-5 py-4 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800 text-center">
                  <span>
                    Vote for spy:
                  </span>
                </h2>
              </header>
            </div>
            <% Player.where.not(id: player.id).each do |player| %>
              <%= link_to "#{player.full_name}", vote_for_spy_game_path(id: game.id, spy_id: player.id), class: 'text-center w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide mb-1' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
      <header class="px-5 py-4 border-b border-gray-100">
        <h2 class="font-semibold text-gray-800">Scoreboard</h2>
      </header>
      <div class="p-3">
        <div class="overflow-x-auto">
          <table class="table-auto w-full">
            <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
              <tr>
                <th class="p-2 whitespace-nowrap">
                  <div class="font-semibold text-left">Place</div>
                </th>
                <th class="p-2 whitespace-nowrap">
                  <div class="font-semibold text-left">Score</div>
                </th>
                <th class="p-2 whitespace-nowrap">
                  <div class="font-semibold text-left">Name</div>
                </th>
              </tr>
            </thead>
            <tbody class="text-sm divide-y divide-gray-100">
              <% game.players.order(score: :desc).each_with_index do |player, index| %>
                <tr>
                  <td class="p-2 whitespace-nowrap">
                    <div class="text-left"><%= index + 1 %></div>
                  </td>
                  <td class="p-2 whitespace-nowrap">
                    <div class="text-left font-medium text-green-500"><%= player.score %></div>
                  </td>
                  <td class="p-2 whitespace-nowrap">
                    <div class="text-lg text-left"><%= player.full_name %></div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<%= turbo_frame_tag @game do %>
  <%= link_to 'Destroy', game_path(@game), class: 'w-auto p-4 bg-gradient-to-tr from-red-600 to-red-300 text-indigo-100 py-2 rounded-md text-lg tracking-wide', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <%= render partial: 'form', locals: { game: @game, header: 'Edit game' } %>
<% end %>

app/views/games/index.html.erb
<div class="h-full container mx-auto px-5 flex">
  <div aria-label="group of cards" tabindex="0" class="focus:outline-none py-8 w-full overflow-auto mb-10">
      <% @games.each do |game| %>
        <div tabindex="0" aria-label="card 1"
          class="focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded">
          <div class="flex items-center border-b border-gray-200 pb-6">
            <div class="flex items-start justify-between w-full">
              <div class="pl-3 w-full">
                <p tabindex="0" class="focus:outline-none text-xl font-medium leading-5 text-gray-800">
                  <%= game.title %>
                </p>
                <p tabindex="0" class="focus:outline-none text-sm leading-normal pt-2 text-gray-500">
                  X members
                </p>
              </div>
              <% if current_user.players.any? { |player| player.game_id == game.id } %>
                <%= link_to 'Join', game_path(game), class: 'w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide' %>
              <% else %>
                <%= link_to 'Join', players_path(game_id: game.id), class: 'w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide', data: { turbo_method: :post } %>
              <% end %>
              <%if false && game.create_user_id == current_user.id %>
                <%= link_to 'Edit', edit_game_path(game), class: 'w-auto p-4 bg-gradient-to-tr from-blue-600 to-indigo-600 text-indigo-100 py-2 rounded-md text-lg tracking-wide' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div>
  <%= render partial: 'form', locals: { game: @game, header: 'Create new game' } %>
</div>

app/views/games/show.html.erb
<%= turbo_stream_from "game_id_#{@game.id}-player_id#{@player.id}" %>
<%= render partial: 'games/game', locals: { game: @game, player: @player, user: current_user } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireWorkshops</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class='h-screen overflow-hidden'>
      <% if current_user %>
        <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
          <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
            <div class="p-4 flex flex-row items-center justify-between">
              <a href="#" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">HotWire Workshops</a>
              <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
                <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
                  <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                  <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
            <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
              <%= link_to 'All games', games_path, class: 'px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline' %>
              <%= link_to 'Create game', new_game_path, class: 'px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline' %>
              <div class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline"><%= current_user.email %></div>
              <%= link_to 'Log out', destroy_user_session_path, class: 'px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline', data: { turbo_method: :delete } %>
            </nav>
          </div>
        </div>
      <% end %>
      <div class="h-full bg-gradient-to-br from-neutral-100 to-stone-300 flex justify-center items-center w-full">
        <%= yield %>
      </div>
    </main>
  </body>
</html>